### ISSUE TITLE
reading output

### ISSUE THREAD

**Issue by snash4** [ansrlab/edgepart#2]
Hi, thanks for sharing the code.
When I run the code, it generates an edgepart file. 
Can you tell me how to read the output of the file?

Thanks.

**Comment by zcz** [comment]
Could you please share one small sample of the file? 
It has been a while and I cannot quite remember the detail.

**Comment by snash4** [comment]
I am partitioning the Orkut file, the program produces a partitioning file. Here is the output of the partitioning file.
<img width="721" alt="Screen Shot 2021-01-28 at 1 32 36 PM" src="https://user-images.githubusercontent.com/642048/106108224-f7b38900-616d-11eb-86ea-1f76f1e9d8a7.png">

**Comment by lqhl** [comment]
hi @snash4 , the parition results are written to a `<basename>.edgepart.<p>` binary file.
the output code is in `edgepart.hpp`. i would suggest you to rewrite `edgepart_writer` to print the results in plain text.

**Comment by lqhl** [comment]
close due to inactive.
